/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuggestiesRouteImport } from './routes/suggesties'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as ProfielRouteImport } from './routes/profiel'
import { Route as LaatLosRouteImport } from './routes/laat-los'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'

const SuggestiesRoute = SuggestiesRouteImport.update({
  id: '/suggesties',
  path: '/suggesties',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfielRoute = ProfielRouteImport.update({
  id: '/profiel',
  path: '/profiel',
  getParentRoute: () => rootRouteImport,
} as any)
const LaatLosRoute = LaatLosRouteImport.update({
  id: '/laat-los',
  path: '/laat-los',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/laat-los': typeof LaatLosRoute
  '/profiel': typeof ProfielRoute
  '/reminders': typeof RemindersRoute
  '/suggesties': typeof SuggestiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/laat-los': typeof LaatLosRoute
  '/profiel': typeof ProfielRoute
  '/reminders': typeof RemindersRoute
  '/suggesties': typeof SuggestiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/laat-los': typeof LaatLosRoute
  '/profiel': typeof ProfielRoute
  '/reminders': typeof RemindersRoute
  '/suggesties': typeof SuggestiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/auth'
    | '/journal'
    | '/laat-los'
    | '/profiel'
    | '/reminders'
    | '/suggesties'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/auth'
    | '/journal'
    | '/laat-los'
    | '/profiel'
    | '/reminders'
    | '/suggesties'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/auth'
    | '/journal'
    | '/laat-los'
    | '/profiel'
    | '/reminders'
    | '/suggesties'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AuthRoute: typeof AuthRoute
  JournalRoute: typeof JournalRoute
  LaatLosRoute: typeof LaatLosRoute
  ProfielRoute: typeof ProfielRoute
  RemindersRoute: typeof RemindersRoute
  SuggestiesRoute: typeof SuggestiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suggesties': {
      id: '/suggesties'
      path: '/suggesties'
      fullPath: '/suggesties'
      preLoaderRoute: typeof SuggestiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiel': {
      id: '/profiel'
      path: '/profiel'
      fullPath: '/profiel'
      preLoaderRoute: typeof ProfielRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laat-los': {
      id: '/laat-los'
      path: '/laat-los'
      fullPath: '/laat-los'
      preLoaderRoute: typeof LaatLosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AuthRoute: AuthRoute,
  JournalRoute: JournalRoute,
  LaatLosRoute: LaatLosRoute,
  ProfielRoute: ProfielRoute,
  RemindersRoute: RemindersRoute,
  SuggestiesRoute: SuggestiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
