/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestModeRouteImport } from './routes/test-mode'
import { Route as SuggestiesRouteImport } from './routes/suggesties'
import { Route as ProfielRouteImport } from './routes/profiel'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AudioDiagnosticsRouteImport } from './routes/audio-diagnostics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RemindersIndexRouteImport } from './routes/reminders.index'
import { Route as NotitiesIndexRouteImport } from './routes/notities.index'
import { Route as LaatLosIndexRouteImport } from './routes/laat-los.index'
import { Route as AgendasIndexRouteImport } from './routes/agendas.index'
import { Route as AgendaIndexRouteImport } from './routes/agenda.index'
import { Route as RemindersNieuwRouteImport } from './routes/reminders.nieuw'
import { Route as RemindersIdRouteImport } from './routes/reminders.$id'
import { Route as LaatLosNieuwRouteImport } from './routes/laat-los.nieuw'
import { Route as LaatLosIdRouteImport } from './routes/laat-los.$id'
import { Route as AgendasCallbackRouteImport } from './routes/agendas.callback'
import { Route as AgendaNieuwRouteImport } from './routes/agenda.nieuw'
import { Route as AgendaIdRouteImport } from './routes/agenda.$id'
import { Route as RemindersIdIndexRouteImport } from './routes/reminders.$id.index'
import { Route as LaatLosIdIndexRouteImport } from './routes/laat-los.$id.index'
import { Route as AgendaIdIndexRouteImport } from './routes/agenda.$id.index'
import { Route as RemindersIdBewerkenRouteImport } from './routes/reminders.$id.bewerken'
import { Route as AgendaIdBewerkenRouteImport } from './routes/agenda.$id.bewerken'
import { Route as ApiPublicHooksSyncIcsRouteImport } from './routes/api/public/hooks/sync-ics'

const TestModeRoute = TestModeRouteImport.update({
  id: '/test-mode',
  path: '/test-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestiesRoute = SuggestiesRouteImport.update({
  id: '/suggesties',
  path: '/suggesties',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfielRoute = ProfielRouteImport.update({
  id: '/profiel',
  path: '/profiel',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioDiagnosticsRoute = AudioDiagnosticsRouteImport.update({
  id: '/audio-diagnostics',
  path: '/audio-diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersIndexRoute = RemindersIndexRouteImport.update({
  id: '/reminders/',
  path: '/reminders/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotitiesIndexRoute = NotitiesIndexRouteImport.update({
  id: '/notities/',
  path: '/notities/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaatLosIndexRoute = LaatLosIndexRouteImport.update({
  id: '/laat-los/',
  path: '/laat-los/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendasIndexRoute = AgendasIndexRouteImport.update({
  id: '/agendas/',
  path: '/agendas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaIndexRoute = AgendaIndexRouteImport.update({
  id: '/agenda/',
  path: '/agenda/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersNieuwRoute = RemindersNieuwRouteImport.update({
  id: '/reminders/nieuw',
  path: '/reminders/nieuw',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersIdRoute = RemindersIdRouteImport.update({
  id: '/reminders/$id',
  path: '/reminders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LaatLosNieuwRoute = LaatLosNieuwRouteImport.update({
  id: '/laat-los/nieuw',
  path: '/laat-los/nieuw',
  getParentRoute: () => rootRouteImport,
} as any)
const LaatLosIdRoute = LaatLosIdRouteImport.update({
  id: '/laat-los/$id',
  path: '/laat-los/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendasCallbackRoute = AgendasCallbackRouteImport.update({
  id: '/agendas/callback',
  path: '/agendas/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaNieuwRoute = AgendaNieuwRouteImport.update({
  id: '/agenda/nieuw',
  path: '/agenda/nieuw',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaIdRoute = AgendaIdRouteImport.update({
  id: '/agenda/$id',
  path: '/agenda/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersIdIndexRoute = RemindersIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RemindersIdRoute,
} as any)
const LaatLosIdIndexRoute = LaatLosIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LaatLosIdRoute,
} as any)
const AgendaIdIndexRoute = AgendaIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgendaIdRoute,
} as any)
const RemindersIdBewerkenRoute = RemindersIdBewerkenRouteImport.update({
  id: '/bewerken',
  path: '/bewerken',
  getParentRoute: () => RemindersIdRoute,
} as any)
const AgendaIdBewerkenRoute = AgendaIdBewerkenRouteImport.update({
  id: '/bewerken',
  path: '/bewerken',
  getParentRoute: () => AgendaIdRoute,
} as any)
const ApiPublicHooksSyncIcsRoute = ApiPublicHooksSyncIcsRouteImport.update({
  id: '/api/public/hooks/sync-ics',
  path: '/api/public/hooks/sync-ics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audio-diagnostics': typeof AudioDiagnosticsRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/onboarding': typeof OnboardingRoute
  '/profiel': typeof ProfielRoute
  '/suggesties': typeof SuggestiesRoute
  '/test-mode': typeof TestModeRoute
  '/agenda/$id': typeof AgendaIdRouteWithChildren
  '/agenda/nieuw': typeof AgendaNieuwRoute
  '/agendas/callback': typeof AgendasCallbackRoute
  '/laat-los/$id': typeof LaatLosIdRouteWithChildren
  '/laat-los/nieuw': typeof LaatLosNieuwRoute
  '/reminders/$id': typeof RemindersIdRouteWithChildren
  '/reminders/nieuw': typeof RemindersNieuwRoute
  '/agenda/': typeof AgendaIndexRoute
  '/agendas/': typeof AgendasIndexRoute
  '/laat-los/': typeof LaatLosIndexRoute
  '/notities/': typeof NotitiesIndexRoute
  '/reminders/': typeof RemindersIndexRoute
  '/agenda/$id/bewerken': typeof AgendaIdBewerkenRoute
  '/reminders/$id/bewerken': typeof RemindersIdBewerkenRoute
  '/agenda/$id/': typeof AgendaIdIndexRoute
  '/laat-los/$id/': typeof LaatLosIdIndexRoute
  '/reminders/$id/': typeof RemindersIdIndexRoute
  '/api/public/hooks/sync-ics': typeof ApiPublicHooksSyncIcsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audio-diagnostics': typeof AudioDiagnosticsRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/onboarding': typeof OnboardingRoute
  '/profiel': typeof ProfielRoute
  '/suggesties': typeof SuggestiesRoute
  '/test-mode': typeof TestModeRoute
  '/agenda/nieuw': typeof AgendaNieuwRoute
  '/agendas/callback': typeof AgendasCallbackRoute
  '/laat-los/nieuw': typeof LaatLosNieuwRoute
  '/reminders/nieuw': typeof RemindersNieuwRoute
  '/agenda': typeof AgendaIndexRoute
  '/agendas': typeof AgendasIndexRoute
  '/laat-los': typeof LaatLosIndexRoute
  '/notities': typeof NotitiesIndexRoute
  '/reminders': typeof RemindersIndexRoute
  '/agenda/$id/bewerken': typeof AgendaIdBewerkenRoute
  '/reminders/$id/bewerken': typeof RemindersIdBewerkenRoute
  '/agenda/$id': typeof AgendaIdIndexRoute
  '/laat-los/$id': typeof LaatLosIdIndexRoute
  '/reminders/$id': typeof RemindersIdIndexRoute
  '/api/public/hooks/sync-ics': typeof ApiPublicHooksSyncIcsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audio-diagnostics': typeof AudioDiagnosticsRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/onboarding': typeof OnboardingRoute
  '/profiel': typeof ProfielRoute
  '/suggesties': typeof SuggestiesRoute
  '/test-mode': typeof TestModeRoute
  '/agenda/$id': typeof AgendaIdRouteWithChildren
  '/agenda/nieuw': typeof AgendaNieuwRoute
  '/agendas/callback': typeof AgendasCallbackRoute
  '/laat-los/$id': typeof LaatLosIdRouteWithChildren
  '/laat-los/nieuw': typeof LaatLosNieuwRoute
  '/reminders/$id': typeof RemindersIdRouteWithChildren
  '/reminders/nieuw': typeof RemindersNieuwRoute
  '/agenda/': typeof AgendaIndexRoute
  '/agendas/': typeof AgendasIndexRoute
  '/laat-los/': typeof LaatLosIndexRoute
  '/notities/': typeof NotitiesIndexRoute
  '/reminders/': typeof RemindersIndexRoute
  '/agenda/$id/bewerken': typeof AgendaIdBewerkenRoute
  '/reminders/$id/bewerken': typeof RemindersIdBewerkenRoute
  '/agenda/$id/': typeof AgendaIdIndexRoute
  '/laat-los/$id/': typeof LaatLosIdIndexRoute
  '/reminders/$id/': typeof RemindersIdIndexRoute
  '/api/public/hooks/sync-ics': typeof ApiPublicHooksSyncIcsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audio-diagnostics'
    | '/auth'
    | '/journal'
    | '/onboarding'
    | '/profiel'
    | '/suggesties'
    | '/test-mode'
    | '/agenda/$id'
    | '/agenda/nieuw'
    | '/agendas/callback'
    | '/laat-los/$id'
    | '/laat-los/nieuw'
    | '/reminders/$id'
    | '/reminders/nieuw'
    | '/agenda/'
    | '/agendas/'
    | '/laat-los/'
    | '/notities/'
    | '/reminders/'
    | '/agenda/$id/bewerken'
    | '/reminders/$id/bewerken'
    | '/agenda/$id/'
    | '/laat-los/$id/'
    | '/reminders/$id/'
    | '/api/public/hooks/sync-ics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audio-diagnostics'
    | '/auth'
    | '/journal'
    | '/onboarding'
    | '/profiel'
    | '/suggesties'
    | '/test-mode'
    | '/agenda/nieuw'
    | '/agendas/callback'
    | '/laat-los/nieuw'
    | '/reminders/nieuw'
    | '/agenda'
    | '/agendas'
    | '/laat-los'
    | '/notities'
    | '/reminders'
    | '/agenda/$id/bewerken'
    | '/reminders/$id/bewerken'
    | '/agenda/$id'
    | '/laat-los/$id'
    | '/reminders/$id'
    | '/api/public/hooks/sync-ics'
  id:
    | '__root__'
    | '/'
    | '/audio-diagnostics'
    | '/auth'
    | '/journal'
    | '/onboarding'
    | '/profiel'
    | '/suggesties'
    | '/test-mode'
    | '/agenda/$id'
    | '/agenda/nieuw'
    | '/agendas/callback'
    | '/laat-los/$id'
    | '/laat-los/nieuw'
    | '/reminders/$id'
    | '/reminders/nieuw'
    | '/agenda/'
    | '/agendas/'
    | '/laat-los/'
    | '/notities/'
    | '/reminders/'
    | '/agenda/$id/bewerken'
    | '/reminders/$id/bewerken'
    | '/agenda/$id/'
    | '/laat-los/$id/'
    | '/reminders/$id/'
    | '/api/public/hooks/sync-ics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudioDiagnosticsRoute: typeof AudioDiagnosticsRoute
  AuthRoute: typeof AuthRoute
  JournalRoute: typeof JournalRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfielRoute: typeof ProfielRoute
  SuggestiesRoute: typeof SuggestiesRoute
  TestModeRoute: typeof TestModeRoute
  AgendaIdRoute: typeof AgendaIdRouteWithChildren
  AgendaNieuwRoute: typeof AgendaNieuwRoute
  AgendasCallbackRoute: typeof AgendasCallbackRoute
  LaatLosIdRoute: typeof LaatLosIdRouteWithChildren
  LaatLosNieuwRoute: typeof LaatLosNieuwRoute
  RemindersIdRoute: typeof RemindersIdRouteWithChildren
  RemindersNieuwRoute: typeof RemindersNieuwRoute
  AgendaIndexRoute: typeof AgendaIndexRoute
  AgendasIndexRoute: typeof AgendasIndexRoute
  LaatLosIndexRoute: typeof LaatLosIndexRoute
  NotitiesIndexRoute: typeof NotitiesIndexRoute
  RemindersIndexRoute: typeof RemindersIndexRoute
  ApiPublicHooksSyncIcsRoute: typeof ApiPublicHooksSyncIcsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-mode': {
      id: '/test-mode'
      path: '/test-mode'
      fullPath: '/test-mode'
      preLoaderRoute: typeof TestModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggesties': {
      id: '/suggesties'
      path: '/suggesties'
      fullPath: '/suggesties'
      preLoaderRoute: typeof SuggestiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiel': {
      id: '/profiel'
      path: '/profiel'
      fullPath: '/profiel'
      preLoaderRoute: typeof ProfielRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-diagnostics': {
      id: '/audio-diagnostics'
      path: '/audio-diagnostics'
      fullPath: '/audio-diagnostics'
      preLoaderRoute: typeof AudioDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders/': {
      id: '/reminders/'
      path: '/reminders'
      fullPath: '/reminders/'
      preLoaderRoute: typeof RemindersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notities/': {
      id: '/notities/'
      path: '/notities'
      fullPath: '/notities/'
      preLoaderRoute: typeof NotitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laat-los/': {
      id: '/laat-los/'
      path: '/laat-los'
      fullPath: '/laat-los/'
      preLoaderRoute: typeof LaatLosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendas/': {
      id: '/agendas/'
      path: '/agendas'
      fullPath: '/agendas/'
      preLoaderRoute: typeof AgendasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/': {
      id: '/agenda/'
      path: '/agenda'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AgendaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders/nieuw': {
      id: '/reminders/nieuw'
      path: '/reminders/nieuw'
      fullPath: '/reminders/nieuw'
      preLoaderRoute: typeof RemindersNieuwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders/$id': {
      id: '/reminders/$id'
      path: '/reminders/$id'
      fullPath: '/reminders/$id'
      preLoaderRoute: typeof RemindersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laat-los/nieuw': {
      id: '/laat-los/nieuw'
      path: '/laat-los/nieuw'
      fullPath: '/laat-los/nieuw'
      preLoaderRoute: typeof LaatLosNieuwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laat-los/$id': {
      id: '/laat-los/$id'
      path: '/laat-los/$id'
      fullPath: '/laat-los/$id'
      preLoaderRoute: typeof LaatLosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendas/callback': {
      id: '/agendas/callback'
      path: '/agendas/callback'
      fullPath: '/agendas/callback'
      preLoaderRoute: typeof AgendasCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/nieuw': {
      id: '/agenda/nieuw'
      path: '/agenda/nieuw'
      fullPath: '/agenda/nieuw'
      preLoaderRoute: typeof AgendaNieuwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/$id': {
      id: '/agenda/$id'
      path: '/agenda/$id'
      fullPath: '/agenda/$id'
      preLoaderRoute: typeof AgendaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders/$id/': {
      id: '/reminders/$id/'
      path: '/'
      fullPath: '/reminders/$id/'
      preLoaderRoute: typeof RemindersIdIndexRouteImport
      parentRoute: typeof RemindersIdRoute
    }
    '/laat-los/$id/': {
      id: '/laat-los/$id/'
      path: '/'
      fullPath: '/laat-los/$id/'
      preLoaderRoute: typeof LaatLosIdIndexRouteImport
      parentRoute: typeof LaatLosIdRoute
    }
    '/agenda/$id/': {
      id: '/agenda/$id/'
      path: '/'
      fullPath: '/agenda/$id/'
      preLoaderRoute: typeof AgendaIdIndexRouteImport
      parentRoute: typeof AgendaIdRoute
    }
    '/reminders/$id/bewerken': {
      id: '/reminders/$id/bewerken'
      path: '/bewerken'
      fullPath: '/reminders/$id/bewerken'
      preLoaderRoute: typeof RemindersIdBewerkenRouteImport
      parentRoute: typeof RemindersIdRoute
    }
    '/agenda/$id/bewerken': {
      id: '/agenda/$id/bewerken'
      path: '/bewerken'
      fullPath: '/agenda/$id/bewerken'
      preLoaderRoute: typeof AgendaIdBewerkenRouteImport
      parentRoute: typeof AgendaIdRoute
    }
    '/api/public/hooks/sync-ics': {
      id: '/api/public/hooks/sync-ics'
      path: '/api/public/hooks/sync-ics'
      fullPath: '/api/public/hooks/sync-ics'
      preLoaderRoute: typeof ApiPublicHooksSyncIcsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgendaIdRouteChildren {
  AgendaIdBewerkenRoute: typeof AgendaIdBewerkenRoute
  AgendaIdIndexRoute: typeof AgendaIdIndexRoute
}

const AgendaIdRouteChildren: AgendaIdRouteChildren = {
  AgendaIdBewerkenRoute: AgendaIdBewerkenRoute,
  AgendaIdIndexRoute: AgendaIdIndexRoute,
}

const AgendaIdRouteWithChildren = AgendaIdRoute._addFileChildren(
  AgendaIdRouteChildren,
)

interface LaatLosIdRouteChildren {
  LaatLosIdIndexRoute: typeof LaatLosIdIndexRoute
}

const LaatLosIdRouteChildren: LaatLosIdRouteChildren = {
  LaatLosIdIndexRoute: LaatLosIdIndexRoute,
}

const LaatLosIdRouteWithChildren = LaatLosIdRoute._addFileChildren(
  LaatLosIdRouteChildren,
)

interface RemindersIdRouteChildren {
  RemindersIdBewerkenRoute: typeof RemindersIdBewerkenRoute
  RemindersIdIndexRoute: typeof RemindersIdIndexRoute
}

const RemindersIdRouteChildren: RemindersIdRouteChildren = {
  RemindersIdBewerkenRoute: RemindersIdBewerkenRoute,
  RemindersIdIndexRoute: RemindersIdIndexRoute,
}

const RemindersIdRouteWithChildren = RemindersIdRoute._addFileChildren(
  RemindersIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudioDiagnosticsRoute: AudioDiagnosticsRoute,
  AuthRoute: AuthRoute,
  JournalRoute: JournalRoute,
  OnboardingRoute: OnboardingRoute,
  ProfielRoute: ProfielRoute,
  SuggestiesRoute: SuggestiesRoute,
  TestModeRoute: TestModeRoute,
  AgendaIdRoute: AgendaIdRouteWithChildren,
  AgendaNieuwRoute: AgendaNieuwRoute,
  AgendasCallbackRoute: AgendasCallbackRoute,
  LaatLosIdRoute: LaatLosIdRouteWithChildren,
  LaatLosNieuwRoute: LaatLosNieuwRoute,
  RemindersIdRoute: RemindersIdRouteWithChildren,
  RemindersNieuwRoute: RemindersNieuwRoute,
  AgendaIndexRoute: AgendaIndexRoute,
  AgendasIndexRoute: AgendasIndexRoute,
  LaatLosIndexRoute: LaatLosIndexRoute,
  NotitiesIndexRoute: NotitiesIndexRoute,
  RemindersIndexRoute: RemindersIndexRoute,
  ApiPublicHooksSyncIcsRoute: ApiPublicHooksSyncIcsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
