/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuggestiesRouteImport } from './routes/suggesties'
import { Route as ProfielRouteImport } from './routes/profiel'
import { Route as LaatLosRouteImport } from './routes/laat-los'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaIndexRouteImport } from './routes/agenda.index'
import { Route as AgendaNieuwRouteImport } from './routes/agenda.nieuw'
import { Route as AgendaIdRouteImport } from './routes/agenda.$id'
import { Route as AgendaIdIndexRouteImport } from './routes/agenda.$id.index'
import { Route as AgendaIdBewerkenRouteImport } from './routes/agenda.$id.bewerken'

const SuggestiesRoute = SuggestiesRouteImport.update({
  id: '/suggesties',
  path: '/suggesties',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfielRoute = ProfielRouteImport.update({
  id: '/profiel',
  path: '/profiel',
  getParentRoute: () => rootRouteImport,
} as any)
const LaatLosRoute = LaatLosRouteImport.update({
  id: '/laat-los',
  path: '/laat-los',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaIndexRoute = AgendaIndexRouteImport.update({
  id: '/agenda/',
  path: '/agenda/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaNieuwRoute = AgendaNieuwRouteImport.update({
  id: '/agenda/nieuw',
  path: '/agenda/nieuw',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaIdRoute = AgendaIdRouteImport.update({
  id: '/agenda/$id',
  path: '/agenda/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaIdIndexRoute = AgendaIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgendaIdRoute,
} as any)
const AgendaIdBewerkenRoute = AgendaIdBewerkenRouteImport.update({
  id: '/bewerken',
  path: '/bewerken',
  getParentRoute: () => AgendaIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/laat-los': typeof LaatLosRoute
  '/profiel': typeof ProfielRoute
  '/suggesties': typeof SuggestiesRoute
  '/agenda/$id': typeof AgendaIdRouteWithChildren
  '/agenda/nieuw': typeof AgendaNieuwRoute
  '/agenda/': typeof AgendaIndexRoute
  '/agenda/$id/bewerken': typeof AgendaIdBewerkenRoute
  '/agenda/$id/': typeof AgendaIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/laat-los': typeof LaatLosRoute
  '/profiel': typeof ProfielRoute
  '/suggesties': typeof SuggestiesRoute
  '/agenda/nieuw': typeof AgendaNieuwRoute
  '/agenda': typeof AgendaIndexRoute
  '/agenda/$id/bewerken': typeof AgendaIdBewerkenRoute
  '/agenda/$id': typeof AgendaIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/laat-los': typeof LaatLosRoute
  '/profiel': typeof ProfielRoute
  '/suggesties': typeof SuggestiesRoute
  '/agenda/$id': typeof AgendaIdRouteWithChildren
  '/agenda/nieuw': typeof AgendaNieuwRoute
  '/agenda/': typeof AgendaIndexRoute
  '/agenda/$id/bewerken': typeof AgendaIdBewerkenRoute
  '/agenda/$id/': typeof AgendaIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/journal'
    | '/laat-los'
    | '/profiel'
    | '/suggesties'
    | '/agenda/$id'
    | '/agenda/nieuw'
    | '/agenda/'
    | '/agenda/$id/bewerken'
    | '/agenda/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/journal'
    | '/laat-los'
    | '/profiel'
    | '/suggesties'
    | '/agenda/nieuw'
    | '/agenda'
    | '/agenda/$id/bewerken'
    | '/agenda/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/journal'
    | '/laat-los'
    | '/profiel'
    | '/suggesties'
    | '/agenda/$id'
    | '/agenda/nieuw'
    | '/agenda/'
    | '/agenda/$id/bewerken'
    | '/agenda/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  JournalRoute: typeof JournalRoute
  LaatLosRoute: typeof LaatLosRoute
  ProfielRoute: typeof ProfielRoute
  SuggestiesRoute: typeof SuggestiesRoute
  AgendaIdRoute: typeof AgendaIdRouteWithChildren
  AgendaNieuwRoute: typeof AgendaNieuwRoute
  AgendaIndexRoute: typeof AgendaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suggesties': {
      id: '/suggesties'
      path: '/suggesties'
      fullPath: '/suggesties'
      preLoaderRoute: typeof SuggestiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiel': {
      id: '/profiel'
      path: '/profiel'
      fullPath: '/profiel'
      preLoaderRoute: typeof ProfielRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laat-los': {
      id: '/laat-los'
      path: '/laat-los'
      fullPath: '/laat-los'
      preLoaderRoute: typeof LaatLosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/': {
      id: '/agenda/'
      path: '/agenda'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AgendaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/nieuw': {
      id: '/agenda/nieuw'
      path: '/agenda/nieuw'
      fullPath: '/agenda/nieuw'
      preLoaderRoute: typeof AgendaNieuwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/$id': {
      id: '/agenda/$id'
      path: '/agenda/$id'
      fullPath: '/agenda/$id'
      preLoaderRoute: typeof AgendaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/$id/': {
      id: '/agenda/$id/'
      path: '/'
      fullPath: '/agenda/$id/'
      preLoaderRoute: typeof AgendaIdIndexRouteImport
      parentRoute: typeof AgendaIdRoute
    }
    '/agenda/$id/bewerken': {
      id: '/agenda/$id/bewerken'
      path: '/bewerken'
      fullPath: '/agenda/$id/bewerken'
      preLoaderRoute: typeof AgendaIdBewerkenRouteImport
      parentRoute: typeof AgendaIdRoute
    }
  }
}

interface AgendaIdRouteChildren {
  AgendaIdBewerkenRoute: typeof AgendaIdBewerkenRoute
  AgendaIdIndexRoute: typeof AgendaIdIndexRoute
}

const AgendaIdRouteChildren: AgendaIdRouteChildren = {
  AgendaIdBewerkenRoute: AgendaIdBewerkenRoute,
  AgendaIdIndexRoute: AgendaIdIndexRoute,
}

const AgendaIdRouteWithChildren = AgendaIdRoute._addFileChildren(
  AgendaIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  JournalRoute: JournalRoute,
  LaatLosRoute: LaatLosRoute,
  ProfielRoute: ProfielRoute,
  SuggestiesRoute: SuggestiesRoute,
  AgendaIdRoute: AgendaIdRouteWithChildren,
  AgendaNieuwRoute: AgendaNieuwRoute,
  AgendaIndexRoute: AgendaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
