// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysapwakidfaxtczlxanu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzYXB3YWtpZGZheHRjemx4YW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgwMDE5NjUsImV4cCI6MjA5MzU3Nzk2NX0.7Nk7J5R6-UoDZ6uGsjc_t8DMb_yD7z0mQV-Jze_l54s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});